# Generated by Django 4.2.2 on 2023-07-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_branches_places_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='branches',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='bankapp.branches'),
            preserve_default=False,
        ),
    ]
